### ISSUE TITLE
./migrate.py / channels doesn't work

### ISSUE THREAD

**Issue by abma** [lunixbochs/uberserver#16]
an idea why this happens?

reading channels
Traceback (most recent call last):
  File "migrate.py", line 87, in <module>
    db.save_channel(c)
  File "./SQLUsers.py", line 504, in save_channel
    session.save(entry)
  File "./sqlalchemy/orm/session.py", line 823, in save
    self._cascade_save_or_update(instance)
  File "./sqlalchemy/orm/session.py", line 852, in _cascade_save_or_update
    for obj, mapper in _cascade_iterator('save-update', instance, halt_on=lambda c:c in self):
  File "./sqlalchemy/orm/session.py", line 1134, in _cascade_iterator
    mapper = _object_mapper(instance)
  File "./sqlalchemy/orm/mapper.py", line 1560, in object_mapper
    raise exceptions.InvalidRequestError("Class '%s' entity name '%s' has no mapper associated with it" % (object.__class__.**name**, getattr(object, '_entity_name', entity_name)))
sqlalchemy.exceptions.InvalidRequestError: Class 'Query' entity name 'None' has no mapper associated with it

**Comment by abma** [comment]
fixed in my fork: https://github.com/abma/uberserver2/commit/799103c100ef26a838e2378b7ceb4cc412346833
